[package]
name = "sspse"
version = "0.1.0"
authors = ["qzed <qzed@users.noreply.github.com>"]
edition = "2018"

[lib]
name="sspse"
path="src/lib.rs"

[dependencies]
hound = "3.4.0"
rustfft = "3.0.0"
gnuplot = "0.0.31"
rand = "0.6.5"
num = "0.2.0"
ndarray = "0.12.1"
sample = { git = "https://github.com/RustAudio/sample" }
GSL = "1.1.0"
